public class Ouput {
	public static void main(String[] args){
	int Value1,Value2,Value4,Value6;
	double Value3, Value7, Value8;
	String Value5;
	Value1 = (1/2);
	Value2 = (1%2);
	Value3 = (1.0/2);
	Value4 = (5+7/2);
	Value5 = ("Beat"+' '+"Army");
	Value6 = (6+13/5-35%3);
	Value7 = (3.5*(5/4));
	Value8 =((3.5*5)/4);  
	System.out.println(Value1);
	System.out.println(Value2);
	System.out.println(Value3);
	System.out.println(Value4);
	System.out.println(Value5);
	System.out.println(Value6);
	System.out.println(Value7);
	System.out.println(Value8);
	}
}
